<!DOCTYPE html>
<html lang="en" ng-app="myapp">
<head>
	<meta charset="UTF-8">
	<title>Document</title>

	<script type="text/javascript" src="bower_components/tinymce/tinymce.js"></script>
	<script src="bower_components/jquery/dist/jquery.js"></script>
	<script src="bower_components/angular/angular.js"></script>
	<script src="bower_components/angular-ui-tinymce/src/tinymce.js"></script>

</head>
<body>

	
	
	<div class="modal fade in show " id="editModal" >
		<form action="" method="POST">
	  <div class="modal-dialog">
	    <div class="modal-content">
	      <div class="modal-header">
	        <button type="button" class="close" ng-click="close()" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
	        <h4 class="modal-title">Login</h4>
	      </div>
	      <div class="modal-body">
	        <p>
	        		<?php if($_isError): ?>
					<div class="alert alert-danger" role="alert">
						<span class="glyphicon glyphicon-exclamation-sign" aria-hidden="true"></span>
						<span class="sr-only">Ошибка:</span>
						Не праильный логин иил пароль
					</div>
	        		<?php endif; ?>

	        		<input name="login" type="login" placeholder="Login"/><br>
	        		<input name="password" type="password" placeholder="Password"/><br>

	        	        </p>
	      </div>
	      <div class="modal-footer">
	        <input type="submit"  class="btn btn-default" data-dismiss="modal" value="Login" />
	      </div>
	    </div><!-- /.modal-content -->
	  </div><!-- /.modal-dialog -->
	  	</form>

	</div><!-- /.modal -->


	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap.css">
	<!-- Optional theme -->
	<link rel="stylesheet" href="bower_components/bootstrap/dist/css/bootstrap-theme.сss">
	<!-- Latest compiled and minified JavaScript -->
	<script src="bower_components/bootstrap/dist/js/bootstrap.js"></script>


</body>
</html>