<?php 
$currentPage = 'about';
include(__DIR__.DIRECTORY_SEPARATOR."header.phtml");
?>

<!--content-->
<div class="content">
    <div class="about-box std">
        <div class="container">
            <div class="row">
                <div class="col-lg-5">
                    <img src="img/about-var1.jpg" alt=""/>
                </div>
                <div class="col-lg-7">
                    <h1 class="page-title">Обо мне</h1>
                    <ul is-editable>
                        <li>Учеба:<br/>
                            В период 2000-2003г. выполнил научную работу "Изучение гемодинамических показателей
                            организма человека
                            во время исследовательской экспедиции по горному Крыму, их взаимосвязь с факторами
                            внешней среды, атмосферным давлением и температурой воздуха"
                        </li>
                        <li>
                            2004-2011г. - проходил обучение в Российском национальном исследовательском медицинском
                            университете
                            им. Н.И.Пирогова на лечебном факультете по специальности "лечебное дело" с дневной/очной
                            формой обучения.
                        </li>
                        <li>2011-2013г. - проходил ординатуру по специальности "урология" в клинике урологии мгсму на
                            базе ГКБ №50, г.Москва
                        </li>
                        <li>В ноябре 2011г. был участником Конгресса секкции Андрологической урологии (ESAU) Европейской
                            ассоциации урологов
                            (EAU), где прослушал секционный курс.
                        </li>
                        <li>19.02.15 Международная школа постдипломного образования по мужскому здоровью PRISM.</li>
                        <li>Профессиональная переподготовка в УЗД (ФГБУ ГНЦ ФМБЦ им. А.И.Бурназяна ФМБА России) -
                            2015г.
                        </li>
                        <li>С января по октябрь 2008г. выполнял функции операционного медбрата российского Национального
                            медико-хирургического
                            центра им. Н.И.Пирогова.
                        </li>
                        <li>С января по сентябрь 2008г. работал лаборантом на кафедре оперативной хирургии и
                            топографической анатомии РГМУ им. Н.И.Пирогова.
                        </li>
                        <li>C 24.10.2013г. и по нынешний день работает как врач уролог в ГП №5, а также в клинике
                            Александра-Мед.
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>

</div>

<!--footer-->
<footer>
    <div class="box">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6 maxheight2 wow fadeInUp">
                    <p class="title">Адрес 1</p>
                    <ul class="list1">
                        <li>Городская поликлиника № 5,<br/>
                            м.Сухаревская,  Даев пер., д. 3,<br/>
                            6 этаж, кабинет 606
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 maxheight2 wow fadeInUp" data-wow-delay="0.1s">
                    <p class="title">Адрес 2</p>
                    <ul class="list1">
                        <li>"Александра Мед" Улица<br/>
                            Кастанаевская, д.9, к.1<br/>
                            Ближайшие станции метро:<br/>
                            Багратионовская<br/>
                            Филевский парк<br/>
                            +74952220514<br/>
                            Запись по телефону</a></li>
                    </ul>
                </div>

                <div class="col-lg-5 col-md-4 col-sm-6 col-lg-offset-1 maxheight2 wow fadeInUp" data-wow-delay="0.3s">
                    <figure class="pull-left"><img src="img/logo-footer.png" alt=""></figure>
                    <div class="txt">
                        <p class="title">
                            Чакирян Микаел Ашотович
                        </p>

                        <p>Врач уролог-андролог<br/>
                            +79266776879<br/>
                            <a href="mailto:dr.chakiryan@yandex.ru">dr.chakiryan@yandex.ru</a></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="box1">
        <div class="container">
            <p class="wow fadeInUp">Чакирян Микаел Ашотович &copy; <em id="copyright-year"></em>. <a
                    href="index-5.html">Все права защищены</a></p>
        </div>
    </div>
</footer>
<script src="js/bootstrap.min.js"></script>
<script src="js/tm-scripts.js"></script>

</body>
</html>