<!DOCTYPE html>
<html lang="en" ng-app="myapp">
<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon"/>
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your keywords">
    <meta name="author" content="Your name">
    <meta name="format-detection" content="telephone=no"/>
    <!--CSS-->
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/camera.css">
    <link rel="stylesheet" href="fonts/font-awesome.css">
    <link rel="stylesheet" href="fonts/lato/stylesheet.css">

    <!--JS-->
    <script src="js/jquery.js"></script>
    <script src="js/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/jquery.mobilemenu.js"></script>
    <script src="js/jquery.equalheights.js"></script>
    <script src="js/camera.js"></script>
    <script src="js/scrollTo.js"></script>
    <script src='http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false%27'></script>

    <script>
        $(document).ready(function () {
            jQuery('.camera_wrap').camera({
                autoAdvance: false,
                pagination: false,
                mobileAutoAdvance: false,
                navigation: false
            });
        });
    </script>
    <!--[if (gt IE 9)|!(IE)]><!-->
    <script src="js/wow/wow.js"></script>
    <script src="js/wow/device.min.js"></script>
    <script src="js/jquery.mobile.customized.min.js"></script>
    <script>
        $(document).ready(function () {
            if ($('html').hasClass('desktop')) {
                new WOW().init();
            }
        });
    </script>

    <script type="text/javascript" src="bower_components/tinymce/tinymce.js"></script>
    <script src="bower_components/angular/angular.js"></script>
    <script src="bower_components/angular-ui-tinymce/src/tinymce.js"></script>
    <script type="text/javascript" src="admin/admin.js"></script>
    <script type="text/javascript" src="admin/editor/AjexFileManager/ajex.js"></script>




    <!--<![endif]-->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

    <div id="ie6-alert" style="width: 100%; text-align:center;">
        <img src="http://beatie6.frontcube.com/images/ie6.jpg" alt="Upgrade IE 6" width="640" height="344" border="0"
             usemap="#Map" longdesc="http://die6.frontcube.com"/>
        <map name="Map" id="Map">
            <area shape="rect" coords="496,201,604,329"
                  href="http://www.microsoft.com/windows/internet-explorer/default.aspx" target="_blank"
                  alt="Download Interent Explorer"/>
            <area shape="rect" coords="380,201,488,329" href="http://www.apple.com/safari/download/" target="_blank"
                  alt="Download Apple Safari"/>
            <area shape="rect" coords="268,202,376,330" href="http://www.opera.com/download/" target="_blank"
                  alt="Download Opera"/>
            <area shape="rect" coords="155,202,263,330" href="http://www.mozilla.com/" target="_blank"
                  alt="Download Firefox"/>
            <area shape="rect" coords="35,201,143,329" href="http://www.google.com/chrome" target="_blank"
                  alt="Download Google Chrome"/>
        </map>
    </div>
    <![endif]-->
</head>
<body>

<div class="modal fade in show " ng-show = "showModal" id="editModal" ng-controller="adminEditor">
      <div class="modal-dialog">
        <div class="modal-content">
          <div class="modal-header">
            <button type="button" class="close" ng-click="close()" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
            <h4 class="modal-title">Modal title</h4>
          </div>
          <div class="modal-body">
            <p>
                {{ showModal }}
                <textarea ui-tinymce="tinymceOptions" ng-model="blockContent">fffff</textarea>

            </p>
          </div>
          <div class="modal-footer">
            <button type="button" ng-click="close()" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="button" ng-click= "save()" class="btn btn-primary">Save changes</button>
          </div>
        </div><!-- /.modal-content -->
      </div><!-- /.modal-dialog -->
    </div><!-- /.modal -->


<!--header-->
<div class="head_box">
    <div class="container">
        <div class="box1 clearfix">
            <p>&nbsp;</p>

            <p class="tel">&nbsp;</p>
        </div>
    </div>
</div>
<header id="stuck_container">
    <div class="container">
        <h1 class="navbar-brand navbar-brand_"><a href="index.html"><img src="img/logo.png" alt="logo">
            <span>Врач уролог-андролог<br/><em>врач ультразвуковой диагностики</em></span>
        </a></h1>
        <nav class="navbar navbar-default navbar-static-top tm_navbar clearfix" role="navigation">
            <ul class="nav sf-menu clearfix">
                <li class="<?=($currentPage == 'index')?'active sub-menu':''?>"><a href="index.php">Главная<i></i></a><span></span></li>
                <li class="<?=($currentPage == 'about')?'active sub-menu':''?>"><a href="index.php?action=about">Обо мне<i></i></a></li>
                <li class="<?=($currentPage == 'service')?'active sub-menu':''?>"><a href="index.php?action=service">Услуги<i></i></a></li>
                <li class="<?=($currentPage == 'testimonials')?'active sub-menu':''?>"><a href="index.php?action=testimonials">Отзывы<i></i></a></li>
                <li ><a href="index.php#contacts-block">Контакты<i></i></a></li>
            </ul>
        </nav>
    </div>
</header>