<!DOCTYPE html>
<html lang="en">
<head>
    <title>Home</title>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="icon" href="img/favicon.ico" type="image/x-icon">
    <link rel="shortcut icon" href="img/favicon.ico" type="image/x-icon"/>
    <meta name="description" content="Your description">
    <meta name="keywords" content="Your keywords">
    <meta name="author" content="Your name">
    <meta name="format-detection" content="telephone=no"/>
    <!--CSS-->
    <link rel="stylesheet" href="css/bootstrap.css">
    <link rel="stylesheet" href="css/style.css">
    <link rel="stylesheet" href="css/animate.css">
    <link rel="stylesheet" href="css/camera.css">
    <link rel="stylesheet" href="fonts/font-awesome.css">
    <link rel="stylesheet" href="fonts/lato/stylesheet.css">

    <!--JS-->
    <script src="js/jquery.js"></script>
    <script src="js/jquery-migrate-1.2.1.min.js"></script>
    <script src="js/jquery.easing.1.3.js"></script>
    <script src="js/jquery.mobilemenu.js"></script>
    <script src="js/jquery.equalheights.js"></script>
    <script src="js/camera.js"></script>
    <script src="js/scrollTo.js"></script>
    <script src='http://maps.googleapis.com/maps/api/js?v=3.exp&sensor=false%27'></script>

    <script>
        $(document).ready(function () {
            jQuery('.camera_wrap').camera({
                autoAdvance: false,
                pagination: false,
                mobileAutoAdvance: false,
                navigation: false
            });
        });
    </script>
    <!--[if (gt IE 9)|!(IE)]><!-->
    <script src="js/wow/wow.js"></script>
    <script src="js/wow/device.min.js"></script>
    <script src="js/jquery.mobile.customized.min.js"></script>
    <script>
        $(document).ready(function () {
            if ($('html').hasClass('desktop')) {
                new WOW().init();
            }
        });
    </script>
    <!--<![endif]-->

    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>

    <div id="ie6-alert" style="width: 100%; text-align:center;">
        <img src="http://beatie6.frontcube.com/images/ie6.jpg" alt="Upgrade IE 6" width="640" height="344" border="0"
             usemap="#Map" longdesc="http://die6.frontcube.com"/>
        <map name="Map" id="Map">
            <area shape="rect" coords="496,201,604,329"
                  href="http://www.microsoft.com/windows/internet-explorer/default.aspx" target="_blank"
                  alt="Download Interent Explorer"/>
            <area shape="rect" coords="380,201,488,329" href="http://www.apple.com/safari/download/" target="_blank"
                  alt="Download Apple Safari"/>
            <area shape="rect" coords="268,202,376,330" href="http://www.opera.com/download/" target="_blank"
                  alt="Download Opera"/>
            <area shape="rect" coords="155,202,263,330" href="http://www.mozilla.com/" target="_blank"
                  alt="Download Firefox"/>
            <area shape="rect" coords="35,201,143,329" href="http://www.google.com/chrome" target="_blank"
                  alt="Download Google Chrome"/>
        </map>
    </div>
    <![endif]-->
</head>
<body>
<!--header-->
<div class="head_box">
    <div class="container">
        <div class="box1 clearfix">
            <p>&nbsp;</p>

            <p class="tel">&nbsp;</p>
        </div>
    </div>
</div>
<header id="stuck_container">
    <div class="container">
        <h1 class="navbar-brand navbar-brand_"><a href="index.html"><img src="img/logo.png" alt="logo"><span>Врач уролог-андролог</span></a></h1>
        <nav class="navbar navbar-default navbar-static-top tm_navbar clearfix" role="navigation">
            <ul class="nav sf-menu clearfix">
                <li class="active sub-menu"><a href="index.html">Главная<i></i></a><span></span></li>
                <li><a href="about.html">Обо мне<i></i></a></li>
                <li><a href="service.html">Услуги<i></i></a></li>
                <li><a href="testimonials.html">Отзывы<i></i></a></li>
                <li><a href="index.html#contacts-block">Контакты<i></i></a></li>
            </ul>
        </nav>
    </div>
</header>
<div class="slider">
    <div class="camera_wrap">
        <div data-src="img/main-pic1.jpg">
            <div class="camera-caption fadeIn"><p class="description">Чакирян Микаел Ашотович</p>

                <p class="title">Решение любых урологических вопросов</p></div>
        </div>
    </div>
</div>
<!--content-->
<div class="content">
    <div class="thumb-box1">
        <div class="container">
            <div class="row">
                <div class="col-lg-6">
                    <ul class="list2">
                        <li class="wow fadeInLeft">
                            <strong class="fa fa-medkit"></strong>

                            <div class="extra-wrap">
                                <p class="title">Комплексное лечение<br>хронического простатита</p>
                            </div>
                        </li>
                        <li class="wow fadeInLeft" data-wow-delay="0.1s">
                            <strong class="fa fa-heart-o"></strong>

                            <div class="extra-wrap">
                                <p class="title">Лечение<br>эректильной дисфункции</p>
                            </div>
                        </li>
                    </ul>
                </div>
                <div class="col-lg-6">
                    <ul class="list2">
                        <li class="wow fadeInRight">
                            <strong class="fa fa-user-md"></strong>

                            <div class="extra-wrap">
                                <p class="title">Лечение мужского<br>бесплодия </p>
                            </div>
                        </li>
                        <li class="wow fadeInRight" data-wow-delay="0.1s">
                            <strong class="fa fa-hospital-o"></strong>

                            <div class="extra-wrap">
                                <p class="title">Увеличение полового<br>члена</p>
                            </div>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
    <div class="stellar-section">
        <div class="thumb-box2" data-stellar-background-ratio="-0.2">
            <div class="container">
                <p class="title wow fadeInUp">Возможность оперативного<br>
                    лечения в ведущих лечебных<br>
                    учреждениях в г.<span>М</span>оскве</p>
                <a href="service.html" class="btn-default btn1 wow fadeInUp">Подробнее</a>
            </div>
        </div>
    </div>
</div>
<section class="content_map">
    <div id="contacts-block"></div>
    <div class="google-map-api">
        <div id="map-canvas" class="gmap"></div>
    </div>
</section>
<!--footer-->
<footer>
    <div class="box">
        <div class="container">
            <div class="row">
                <div class="col-lg-3 col-md-4 col-sm-6 maxheight2 wow fadeInUp">
                    <p class="title">Адрес 1</p>
                    <ul class="list1">
                        <li>Городская поликлиника № 5,<br/>
                            м.Сухаревская,  Даев пер., д. 3,<br/>
                        6 этаж, кабинет 606
                        </li>
                    </ul>
                </div>
                <div class="col-lg-3 col-md-4 col-sm-6 maxheight2 wow fadeInUp" data-wow-delay="0.1s">
                    <p class="title">Адрес 2</p>
                    <ul class="list1">
                        <li>"Александра Мед" Улица<br/>
                            Кастанаевская, д.9, к.1<br/>
                            Ближайшие станции метро:<br/>
                            Багратионовская<br/>
                            Филевский парк<br/>
                            +74952220514<br/>
                            Запись по телефону</a></li>
                    </ul>
                </div>

                <div class="col-lg-5 col-md-4 col-sm-6 col-lg-offset-1 maxheight2 wow fadeInUp" data-wow-delay="0.3s">
                    <figure class="pull-left"><img src="img/logo-footer.png" alt=""></figure>
                    <div class="txt">
                        <p class="title">
                            Чакирян Микаел Ашотович
                        </p>

                        <p>Врач уролог-андролог<br/>
                            +79266776879<br/>
                            <a href="mailto:dr.chakiryan@yandex.ru">dr.chakiryan@yandex.ru</a></p>
                    </div>

                </div>
            </div>
        </div>
    </div>
    <div class="box1">
        <div class="container">
            <p class="wow fadeInUp">Чакирян Микаел Ашотович &copy; <em id="copyright-year"></em>. <a
                    href="index-5.html">Все права защищены</a></p>
        </div>
    </div>
</footer>
<script src="js/bootstrap.min.js"></script>
<script src="js/tm-scripts.js"></script>
<script type="text/javascript">
google_api_map_init();
function google_api_map_init() {
    var map;
    var coordData = new google.maps.LatLng(parseFloat(40.646197), parseFloat(-73.9724068, 14));
    var markCoord1 = new google.maps.LatLng(parseFloat(40.643180), parseFloat(-73.9874068, 14));
    var markCoord2 = new google.maps.LatLng(parseFloat(40.6422180), parseFloat(-73.9784068, 14));
    var markCoord3 = new google.maps.LatLng(parseFloat(40.6482180), parseFloat(-73.9724068, 14));
    var markCoord4 = new google.maps.LatLng(parseFloat(40.6442180), parseFloat(-73.9664068, 14));
    var markCoord5 = new google.maps.LatLng(parseFloat(40.6379180), parseFloat(-73.9552068, 14));
    var marker;

    var styleArray = [
        {
            "featureType": "water",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#c2dbec"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "featureType": "landscape",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#d2e4f1"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#a1c7e1"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "featureType": "road.highway",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "color": "#97c1de"
                },
                {
                    "lightness": 0
                },
                {
                    "weight": 1
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#dae9f3"
                },
                {
                    "weight": 2
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "featureType": "road.arterial",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "color": "#c3dbec"
                },
                {
                    "lightness": 0
                },
                {
                    "weight": 1
                }
            ]
        },
        {
            "featureType": "road.local",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#c3dbec"
                },
                {
                    "weight": 0.5
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "featureType": "poi",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#cee1ef"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "elementType": "labels.text.stroke",
            "stylers": [
                {
                    "visibility": "on"
                },
                {
                    "color": "#cadfef"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "elementType": "labels.text.fill",
            "stylers": [
                {
                    "saturation": 36
                },
                {
                    "color": "#85b6d8"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "elementType": "labels.icon",
            "stylers": [
                {
                    "visibility": "off"
                }
            ]
        },
        {
            "featureType": "transit",
            "elementType": "geometry",
            "stylers": [
                {
                    "color": "#abcde5"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "featureType": "administrative",
            "elementType": "geometry.fill",
            "stylers": [
                {
                    "color": "#ff0000"
                },
                {
                    "lightness": 0
                }
            ]
        },
        {
            "featureType": "administrative",
            "elementType": "geometry.stroke",
            "stylers": [
                {
                    "color": "#abcde5"
                },
                {
                    "lightness": 0
                },
                {
                    "weight": 1.2
                }
            ]
        }
    ]

    var markerIcon = {
        url: "img/gmap_marker.png",
        size: new google.maps.Size(114, 114),
        origin: new google.maps.Point(0, 0),
        anchor: new google.maps.Point(21, 70)
    };

    function initialize() {
        var mapOptions = {
            zoom: 14,
            center: coordData,
            scrollwheel: false,
            styles: styleArray
        }

        var contentString = "<div></div>";
        var infowindow = new google.maps.InfoWindow({
            content: contentString,
            maxWidth: 200
        });

        var map = new google.maps.Map(document.getElementById("map-canvas"), mapOptions);
        marker = new google.maps.Marker({
            map: map,
            position: markCoord1,
            icon: markerIcon
        });

        var contentString = '<div id="content">' +
                '<div id="siteNotice">' +
                '</div>' +
                '<div id="bodyContent">' +
                '<p>Адрес:  Городская поликлиника № 5 </p>' +
                '<p>ЦАО, метро Сухаревская, Даев пер., д. 3</p>'+
                '<p>6 этаж, кабинет 606</p>'+
                '<strong>+79266776879</strong>' +
                '<p><a href="mailto:dr.chakiryan@yandex.ru">dr.chakiryan@yandex.ru</a></p>' +
                '</div>' +
                '</div>';

        var infowindow = new google.maps.InfoWindow({
            content: contentString
        });


        google.maps.event.addListener(marker, 'click', function () {
            infowindow.open(map, marker);
            $('.gm-style-iw').parent().parent().addClass("gm-wrapper");
        });


        google.maps.event.addDomListener(window, 'resize', function () {

            map.setCenter(coordData);
s
            var center = map.getCenter();
        });
    }

    google.maps.event.addDomListener(window, "load", initialize);

}
</script>
</body>
</html>