  <div class="container">
        <h1 class="navbar-brand navbar-brand_"><a href="index.html"><img src="img/logo.png" alt="logo"><span>Врач уролог-андролог</span></a></h1>
        <nav class="navbar navbar-default navbar-static-top tm_navbar clearfix" role="navigation">
            <ul class="nav sf-menu clearfix">
                <li class="active sub-menu"><a href="index.html">Главная<i></i></a><span></span></li>
                <li><a href="about.html">Обо мне<i></i></a></li>
                <li><a href="service.html">Услуги<i></i></a></li>
                <li><a href="testimonials.html">Отзывы<i></i></a></li>
                <li><a href="index.html#contacts-block">Контакты<i></i></a></li>
            </ul>
        </nav>
    </div>